fourth revision - Save the Environment
fix: basic travis environment, exports to build.sh now
imp: logging and annotation of first error per step
imp: docs + example
new: TRAVIS_ALLOW_FAILURE / with.allow_failure

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -17,17 +17,25 @@ inputs:
     default: ''
     required: true
 
+  allow_failure:
+    description: 'allow to fail, see TRAVIS_ALLOW_FAILURE'
+    default: false
+    required: false
+
 runs:
   using: composite
 
   steps:
     - shell: bash
-      env:
-        INPUT_STAGES: ${{ inputs.stages }}
-        INPUT_FILE: ${{ inputs.file }}
 
       run: |
-        TRAVIS_BRANCH="${TRAVIS_BRANCH:-${{ github.head_ref }}}"
+        gh_refname() { echo "${1#refs/*/}"; }
+        :
+        CI="${CI:-true}"
+        HAS_JOSH_K_SEAL_OF_APPROVAL="${HAS_JOSH_K_SEAL_OF_APPROVAL:-true}"
+        HAS_ANTARES_THREE_LITTLE_FRONZIES_BADGE="${HAS_ANTARES_THREE_LITTLE_FRONZIES_BADGE:-true}"
+        TRAVIS_ALLOW_FAILURE="${TRAVIS_ALLOW_FAILURE:-${{ inputs.allow_failure }}}"
+        TRAVIS_BRANCH="$(gh_refname "${TRAVIS_BRANCH:-${GITHUB_BASE_REF:-$GITHUB_REF}}")"
         # TRAVIS_BUILD_ID
         # TRAVIS_BUILD_NUMBER
         # TRAVIS_COMMIT
@@ -36,25 +44,38 @@ runs:
         # TRAVIS_JOB_ID
         TRAVIS_PULL_REQUEST="${TRAVIS_PULL_REQUEST:-${{ github.event.number }}}"
         TRAVIS_REPO_SLUG="${TRAVIS_REPO_SLUG:-${{ github.repository }}}"
-        CI="${CI:-true}"
-        HAS_JOSH_K_SEAL_OF_APPROVAL="${HAS_JOSH_K_SEAL_OF_APPROVAL:-true}"
-        HAS_ANTARES_THREE_LITTLE_FRONZIES_BADGE="${HAS_ANTARES_THREE_LITTLE_FRONZIES_BADGE:-true}"
+        TRAVIS_YAML_FILE="${TRAVIS_YAML_FILE:-${{ inputs.file }}}"
         :
-        ghexport() { echo "$1=${!1}" >> $GITHUB_ENV; }
-        ghexport TRAVIS_BRANCH
-        ghexport TRAVIS_EVENT_TYPE
-        ghexport TRAVIS_PULL_REQUEST
-        ghexport TRAVIS_REPO_SLUG
+        printf '::group::env: \033[34m%s\033[0m\n' ".travis.yml"
+        gh_export() { export "$1"; echo "$1=${!1}" >> $GITHUB_ENV; printf '  %s: %s\n' "$1" "${!1}"; }
+        gh_export TRAVIS_ALLOW_FAILURE
+        gh_export TRAVIS_BRANCH
+        gh_export TRAVIS_EVENT_TYPE
+        gh_export TRAVIS_PULL_REQUEST
+        gh_export TRAVIS_REPO_SLUG
+        gh_export TRAVIS_YAML_FILE
+        printf '::endgroup::\n'
         :
-        "$GITHUB_ACTION_PATH"/lib/travis-script-builder.php $INPUT_STAGES > "$GITHUB_ACTION_PATH"/build.sh
-        if [[ "$TRAVIS_REPO_SLUG" = "ktomk/run-travis-yml" ]]; then
-          /bin/bash "$GITHUB_ACTION_PATH"/build.sh || :
-          echo "(the build error is by intention)"
-          echo "(this is ktomk/run-travis-yml and can not fail)"
-          echo "(your build would have failed)"
-        else
+        "$GITHUB_ACTION_PATH"/lib/travis-script-builder.php --file "$TRAVIS_YAML_FILE" "${{ inputs.stages }}" \
+          > "$GITHUB_ACTION_PATH"/build.sh
+        :
+        set +e
           /bin/bash "$GITHUB_ACTION_PATH"/build.sh
+          build_result=$?
+          TRAVIS_TEST_RESULT=$build_result
+        set -e
+        :
+        if [[ $build_result -ne 0 ]] && [[ "$TRAVIS_ALLOW_FAILURE" = "true" ]]; then
+          printf '\033[34mTRAVIS_ALLOW_FAILURE for build exit status %s\033[0m\n' "$build_result"
+          build_result=0 # silent
         fi
         :
-        ghexport TRAVIS_CMD
-        ghexport TRAVIS_TEST_RESULT
+        TRAVIS_YAML_FILE_LAST="${TRAVIS_YAML_FILE}"
+        TRAVIS_YAML_FILE=
+        printf '::group::env: \033[34m%s\033[0m (post)\n' ".travis.yml"
+        gh_export TRAVIS_TEST_RESULT
+        gh_export TRAVIS_YAML_FILE
+        gh_export TRAVIS_YAML_FILE_LAST
+        printf '::endgroup::\n'
+        :
+        exit $build_result
